### ISSUE TITLE
Vita3K is technically not the first Vita emulator

### ISSUE THREAD

**Issue by hcorion** [Vita3K/Vita3K.github.io#4]
You mention at least once that Vita3k is the first vita emulator, which is not exactly true, as RPCS3 was technically the first.

This could be easily be reworded to something more accurate, as RPCS3's vita emulation was extremely poor.

Perhaps, World's first functional Vita emulator?

**Comment by VelocityRa** [comment]
Hm, but if we call it "functional" people will have expectations that Vita3K doesn't meet yet.

**Comment by VelocityRa** [comment]
How functional was RPCS3a's support btw?

**Comment by Rinnegatamante** [comment]
RPCS3 since when can be defined a Vita emulator? It never run anything for years, not even an hello world.

**Comment by hcorion** [comment]
Well, RPCS3 has had some basic vita emulation since 2013, and I was under the impression that it could run hello world?

**Comment by petmac** [comment]
I agree with @hcorion - we should delete/change the text to no longer say we are the first.

**Comment by dracc** [comment]
I'd argue this issue should be closed as #68 fixed the problem.
