### ISSUE TITLE
translate the page into Spanish LT?

### ISSUE THREAD

**Issue by killerjn** [Vita3K/Vita3K.github.io#52]

**Comment by IllusionMan1212** [comment]
You can just add the translations to both index.js and compatibility.js and someone will integrate it later.
(P.S if you have further questions you can join our discord server instead of us spamming github)

**Comment by killerjn** [comment]
want to help is spam?

**Comment by IllusionMan1212** [comment]
well no, we can use all the help we can get.
what i meant was if we're gonna keep talking like this it's just gonna spam the issue, plus i reply faster on discord but whatever suits you :)

**Comment by killerjn** [comment]
I do not think it's necessary anymore

**Comment by Thehache** [comment]
**what idiot people just try to help, I leave the meaning of the word spam   **
[https://en.wikipedia.org/wiki/Spam](url)
**Does it mean that opening a problem for you is spam?**
